### ISSUE TITLE
ErrImageNeverPull Error

### ISSUE THREAD

**Issue by hafizmujadid** [PipelineAI/pipeline#279]
Hi,

I am trying to follow [this](https://github.com/PipelineAI/pipeline/tree/master/docs/quickstart/kubernetes) link to deploy model in local kubernetes cluster. When I execute the step "Deploy Istio to Cluster" and run command `kubectl get all`. It does not produce the expected output. Rather it displays `ErrImageNeverPull` in status column. The output of this command is in the attached image.
![output](https://user-images.githubusercontent.com/4970277/44986205-3932b080-af83-11e8-8ff2-b00589850de7.png)

I also noticed the issues in documentation like if we pull the repository, then there is no **mnist-v3** folder rather it is **mnist-v1**. Similarly, json file **./tensorflow/mnist-v3/input/predict/test_request.json** does not exist. 
Waiting for the response. 

Thanks

**Comment by cfregly** [comment]
@hafizmujadid i updated the docs to use `v1` instead of `v3` - as well as `pipeline_test_request.json`

re: `ErrImageNeverPull`.  try this file again:  

https://github.com/PipelineAI/pipeline/blob/master/docs/quickstart/kubernetes/istio-0.7.1-default-namespace.yaml

i just changed the default `imagePullPolicy` to Always (instead of Never).

we use Never internally because we have a separate step to download the images - and we like upfront, deterministic downloads of these images.

**Comment by cfregly** [comment]
please re-open if you're still having issues

**Comment by hafizmujadid** [comment]
Hi @cfregly ,
Thanks for the updates. I tried it now and previous issues are fixed but there is still error at the next step. When I execute
 `kubectl get pod --namespace=default`, 
then there is still 
`ErrImageNeverPull` error. 
I am attaching the output of this command. 
![output](https://user-images.githubusercontent.com/4970277/45024077-76a54580-b038-11e8-8092-35674aad000f.png)

Waiting for the response. thanks
