### ISSUE TITLE
 error validating data

### ISSUE THREAD

**Issue by hafizmujadid** [PipelineAI/pipeline#280]
Hi,
I am following [this](https://github.com/PipelineAI/pipeline/tree/master/docs/quickstart/kubernetes) guide to setup pipelineAI on kubernetes at my local Linux machine. When I execute the command 
`pipeline predict-kube-start --model-name=mnist --model-tag=v1a`

It ends with following error:

`error: error validating ".pipeline-generated-predict-mnist-svc.yaml-istio": error validating data: [unknown object type "nil" in Service.metadata.labels.runtime, unknown object type "nil" in Service.metadata.labels.type, unknown object type "nil" in Service.spec.selector.runtime, unknown object type "nil" in Service.spec.selector.type]; if you choose to ignore these errors, turn validation off with --validate=false`

And if I execute the command after this
 `kubectl get pod --namespace=default`

It displays the following output.
![output](https://user-images.githubusercontent.com/4970277/45084470-b3d40b00-b0fe-11e8-8424-7cecf1ec4466.png)

Waiting for the response. 
thanks

**Comment by ericwangqing** [comment]
Actually I found both generated svc.yaml and deploy.yaml are not valid. The 'runtime' and 'type' labels are nil in them, which cause k8s failed.  

Here's my recipe. Since there's no way to pass args to the kubectl called behind the pipeline cmd, I have to hack the installed cli-pipeline.py by adding the --validate=false flag at 3768 line, in the _istio_apply method.  After that the pipeline works smoothly :)  
![image](https://user-images.githubusercontent.com/364773/45249022-947ded80-b34b-11e8-87bc-a4fd1a805a5c.png)
----
BUT, it just a violent hack. Let's wait for the official fix.

**Comment by hafizmujadid** [comment]
Hi,
sure will be waiting for the fix.

**Comment by cfregly** [comment]
@ericwangqing this is related to #283, actually.  fixing now.
